/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutDivider: typeof import('@nutui/nutui')['Divider']
    NutNavbar: typeof import('@nutui/nutui')['Navbar']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    NutSideNavbar: typeof import('@nutui/nutui')['SideNavbar']
    NutSideNavbarItem: typeof import('@nutui/nutui')['SideNavbarItem']
    NutTabPane: typeof import('@nutui/nutui')['TabPane']
    NutTabs: typeof import('@nutui/nutui')['Tabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
